/**
 * @package arm4slide
 * File: frontend_js.js
 * Description: js code for the frontend side of arm4slide plugin.
 * Requires: mooTools-core, mooTools-more, class-arm4slide
**/

window.addEvent('domready', function() {

	arm4_slider = new arm4slide( slider.wrapper_id, {
		wrapper_id: slider.wrapper_id,
		wrapper_width: slider.wrapper_width,
		wrapper_height: slider.wrapper_height,
		wrapper_texture: slider.wrapper_texture,
		wrapper_background: slider.wrapper_background,
		wrapper_shadow_x: slider.wrapper_shadow_x,
		wrapper_shadow_y: slider.wrapper_shadow_y,
		wrapper_shadow_blur: slider.wrapper_shadow_blur,
		wrapper_shadow_color: slider.wrapper_shadow_color,
		wrapper_border_radius: slider.wrapper_border_radius,
		wrapper_padding: slider.wrapper_padding,
		slides_class: slider.slides_class,
		slides_shadow_x: slider.slides_shadow_x,
		slides_shadow_y: slider.slides_shadow_y,
		slides_shadow_blur: slider.slides_shadow_blur,
		slides_shadow_color: slider.slides_shadow_color,
		slides_border_radius: slider.slides_border_radius,
		captions_class: slider.captions_class,
		captions_title_pos: slider.title_pos,
		captions_title_fontcolor: slider.title_fontcolor,
		captions_title_size: slider.title_size,
		captions_title_font_shadow_x: slider.title_font_shadow_x,
		captions_title_font_shadow_y: slider.title_font_shadow_y,
		captions_title_font_shadow_blur: slider.title_font_shadow_blur,
		captions_title_font_shadow_color: slider.title_font_shadow_color,
		captions_title_texture: slider.title_texture,
		captions_title_background: slider.title_background,
		captions_title_shadow_x: slider.title_shadow_x,
		captions_title_shadow_y: slider.title_shadow_y,
		captions_title_shadow_blur: slider.title_shadow_blur,
		captions_title_shadow_color: slider.title_shadow_color,
		captions_title_padding: slider.title_padding,
		captions_content_pos: slider.content_pos,
		captions_content_width: slider.content_width,
		captions_content_fontcolor: slider.content_fontcolor,
		captions_content_size: slider.content_size,
		captions_content_font_shadow_x: slider.content_font_shadow_x,
		captions_content_font_shadow_y: slider.content_font_shadow_y,
		captions_content_font_shadow_blur: slider.content_font_shadow_blur,
		captions_content_font_shadow_color: slider.content_font_shadow_color,
		captions_content_texture: slider.content_texture,
		captions_content_background: slider.content_background,
		captions_content_shadow_x: slider.content_shadow_x,
		captions_content_shadow_y: slider.content_shadow_y,
		captions_content_shadow_blur: slider.content_shadow_blur,
		captions_content_shadow_color: slider.content_shadow_color,
		captions_content_padding: slider.content_padding,
		control_class: slider.control_class,
		control_type: slider.control_type,
		control_pos: slider.control_pos,
		control_width: slider.control_width,
		control_height: slider.control_height,
		control_texture: slider.control_texture,
		control_background: slider.control_background,
		control_color: slider.control_color,
		control_shadow_x: slider.control_shadow_x,
		control_shadow_y: slider.control_shadow_y,
		control_shadow_blur: slider.control_shadow_blur,
		control_shadow_color: slider.control_shadow_color,
		control_border_radius: slider.control_border_radius,
		control_padding: slider.control_padding,
		control_margin: slider.control_margin,
		anim_first: slider.anim_first,
		anim_movetime: slider.anim_movetime,
		anim_movetype_out: slider.anim_movetype_out,
		anim_movetype_in: slider.anim_movetype_in,
		anim_title_move: slider.anim_title_move,
		anim_title_type: slider.anim_title_type,
		anim_content_move: slider.anim_content_move,
		anim_content_type: slider.anim_content_type,
		anim_pause_in: slider.anim_pause_in,
		anim_pause_out: slider.anim_pause_out,
		readmore: slider.readmore,
		link: slider.link,
		auto: slider.auto,
		//transition: '3d',
		//transitionFallback: 'slide'
		captionPosition: null,
		narrow: false,
	});

});
